In [1]:
import pandas as pd
from utils import helpers
from validations import logic
import datetime
from utils import main_logic



CRPATH = "c:/Users/admin/lab/alex/etl_drones/v3/data/s3/cr.csv" # input("Drop Customer Remitance csv file: ")
NSPATH = "c:/Users/admin/lab/alex/etl_drones/v3/data/s3/ns.csv" #  input("Drop Netsuite csv file: ")

# CRPATH = r"C:\Users\admin\lab\alex\etl_drones\v3\fileSet\ztest\cr2nm.csv"

In [ ]:
tb_credit, tb_payments = main_logic.run_logic(CRPATH=CRPATH, NSPATH=NSPATH)

In [3]:
f = {0:'data/noCM_cinc.csv', # there is no credit 
    1:'data/noCM_cinn.csv', # there is no credit
    2:'data/CM_cinc.csv',
    3:'data/CM_cinn.csv',
    4:'data/noCM_B_cinc.csv',
    5:'data/noCM_B_cinn.csv'
    }

CRPATH = f[0]
NSPATH = f[1]

crin, crcm, nsin, nscm, CONST_payment_ref, CONST_payment_amt, CONST_count_of_credits_original = helpers.getData(CRPATH, NSPATH)


crnsINp, crnsCMp = helpers.get_processed(crin, nsin, crcm, nscm, CONST_payment_ref, CONST_payment_amt)

In [27]:
# crin, crcm, nsin, nscm, CONST_payment_ref, CONST_payment_amt, CONST_count_of_credits_original = helpers.getData(CRPATH, NSPATH)

In [3]:
def testing():

    crin, crcm, nsin, nscm, CONST_payment_ref, \
    CONST_payment_amt, CONST_count_of_credits_original, \
    CONST_payment_dt, CONST_payment_typ = helpers.getData(CRPATH, NSPATH) 
    # logging.debug(f"{CONST_payment_amt=} | {CONST_payment_ref=} | {CONST_count_of_credits_original=}")

    crnsINp, crnsCMp = helpers.get_processed(crin, nsin, crcm, nscm, CONST_payment_ref, CONST_payment_amt, CONST_payment_typ)




    if CONST_count_of_credits_original > 0:
        print("✅ : Credits found")
        print("✅ : processing data...")

        ccc = helpers.apply_credit(crnsINp, crnsCMp)
        credits_data = helpers.prep_cosmetic_credit_sheet(ccc, CONST_payment_ref)

        # Download CREDIT CSV
        # helpers.save_csv('credits.csv', credits_data)




        ccc = helpers.process_discount_again(ccc, CONST_payment_ref, CONST_payment_amt)

        if logic.check_invoice_application_sum(ccc, CONST_payment_amt)[1]:
            payments_data = helpers.prep_cosmetic_payment_sheet(ccc, CONST_payment_dt)
            # helpers.save_csv('payments.csv', payments_data)
            print("Credits found, Data Saved Successfully")

    else:
        print("No credits found")
        print("processing data...")

        if logic.check_invoice_application_sum(crnsINp, CONST_payment_amt):
            payments_data = helpers.prep_cosmetic_payment_sheet(crnsINp, CONST_payment_dt)
            # helpers.save_csv('payments.csv', payments_data)
            print("No credits found, Data Saved Successfully")

    payments_data = helpers.force_convert_dtypes(payments_data, 'py')
    # if (CONST_count_of_credits_original > 0):
    #     return credits_data, payments_data
    # else:
    #     return helpers.pd.DataFrame(), payments_data

# d = testing(CRPATH, NSPATH)

✅ : Valid Template Structure, for cr
✅ : Valid Template Structure, for ns
✅ : Credits found
✅ : processing data...
✅ : Valid Invoice Application Sum, INV total: 8642.66, Payment amt: 8642.66
Credits found, Data Saved Successfully

In [13]:
ccc

,Date,Customer Internal ID,Internal ID,PO#,Amount Remaining,Amount Paid,Invoice Application,Payment #,Payment Amount,External ID,Memo,Discount Amount,Discount Percent,WithinTolerence
0,4/25/2022,4871,3910528,PO000091996339,1136.36,1136.36,0.00,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
1,5/2/2022,4871,3982710,PO000092103121,877.61,877.61,3.26,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
2,4/25/2022,4871,3910438,PO000092023985,874.35,874.35,476.15,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
3,4/26/2022,4871,3918392,PO000092041619,874.35,874.35,874.35,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
7,4/25/2022,4871,3910431,PO000092008533,529.30,529.30,529.30,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
9,5/2/2022,4871,3982715,PO000092126065,529.30,529.30,529.30,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
8,5/2/2022,4871,3982716,PO000092122762,529.30,529.30,529.30,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
10,5/2/2022,4871,3982708,PO000092103754,529.30,529.30,529.30,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
6,4/25/2022,4871,3910428,PO000092019736,529.30,529.30,529.30,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
5,5/2/2022,4871,3982719,PO000092113553,529.30,529.30,529.30,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
4,4/25/2022,4871,3910417,PO000092001443,529.30,529.30,529.30,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
11,4/26/2022,4871,3918289,PO000092033698,398.20,398.20,398.20,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
12,4/26/2022,4871,3917693,PO000092040626,398.20,398.20,398.20,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
13,4/26/2022,4871,3917698,PO000092043615,398.20,398.20,398.20,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
14,4/25/2022,4871,3910423,PO000092030169,398.20,398.20,398.20,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
15,4/25/2022,4871,3910526,PO000091998818,398.20,398.20,398.20,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
16,4/25/2022,4871,3910515,PO000092010761,398.20,398.20,398.20,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
17,4/25/2022,4871,3910436,PO000092006406,398.20,398.20,398.20,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
18,4/25/2022,4871,3910427,PO000091995573,398.20,398.20,398.20,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No
19,5/2/2022,4871,3982720,PO000092127264,398.20,398.20,398.20,ACH999999.0,8642.66,PAACH999999.0,ACH 999999.0,0.0,0.0,No

In [12]:
payments_data

,Date,Customer ID,Payment #,Invoice Internal,Payment Amount,Invoice Application,Discount,External ID,Memo
0,5/16/2022,4871,ACH999999.0,3910528,8642.66,0.00,0.0,PAACH999999.0,ACH 999999.0
1,5/16/2022,4871,ACH999999.0,3982710,8642.66,3.26,0.0,PAACH999999.0,ACH 999999.0
2,5/16/2022,4871,ACH999999.0,3910438,8642.66,476.15,0.0,PAACH999999.0,ACH 999999.0
3,5/16/2022,4871,ACH999999.0,3918392,8642.66,874.35,0.0,PAACH999999.0,ACH 999999.0
7,5/16/2022,4871,ACH999999.0,3910431,8642.66,529.30,0.0,PAACH999999.0,ACH 999999.0
9,5/16/2022,4871,ACH999999.0,3982715,8642.66,529.30,0.0,PAACH999999.0,ACH 999999.0
8,5/16/2022,4871,ACH999999.0,3982716,8642.66,529.30,0.0,PAACH999999.0,ACH 999999.0
10,5/16/2022,4871,ACH999999.0,3982708,8642.66,529.30,0.0,PAACH999999.0,ACH 999999.0
6,5/16/2022,4871,ACH999999.0,3910428,8642.66,529.30,0.0,PAACH999999.0,ACH 999999.0
5,5/16/2022,4871,ACH999999.0,3982719,8642.66,529.30,0.0,PAACH999999.0,ACH 999999.0
4,5/16/2022,4871,ACH999999.0,3910417,8642.66,529.30,0.0,PAACH999999.0,ACH 999999.0
11,5/16/2022,4871,ACH999999.0,3918289,8642.66,398.20,0.0,PAACH999999.0,ACH 999999.0
12,5/16/2022,4871,ACH999999.0,3917693,8642.66,398.20,0.0,PAACH999999.0,ACH 999999.0
13,5/16/2022,4871,ACH999999.0,3917698,8642.66,398.20,0.0,PAACH999999.0,ACH 999999.0
14,5/16/2022,4871,ACH999999.0,3910423,8642.66,398.20,0.0,PAACH999999.0,ACH 999999.0
15,5/16/2022,4871,ACH999999.0,3910526,8642.66,398.20,0.0,PAACH999999.0,ACH 999999.0
16,5/16/2022,4871,ACH999999.0,3910515,8642.66,398.20,0.0,PAACH999999.0,ACH 999999.0
17,5/16/2022,4871,ACH999999.0,3910436,8642.66,398.20,0.0,PAACH999999.0,ACH 999999.0
18,5/16/2022,4871,ACH999999.0,3910427,8642.66,398.20,0.0,PAACH999999.0,ACH 999999.0
19,5/16/2022,4871,ACH999999.0,3982720,8642.66,398.20,0.0,PAACH999999.0,ACH 999999.0